language: python
python:
  - '2.7'
script: python manage.py help
env: SECRET_KEY=1234 DEBUG=False
deploy:
  provider: heroku
  app: socrates-conf-stage
  strategy: git
  api_key:
    secure: zo2B3kTafqduYNxTfKhHESZUvKpn4a7py8/b5l6w5SuSTemVk6MO/6OOf/kRDvciZwJ05M0bo6x8FF0y874SwZd146PY80oEK9aDHLMYQYhI708d5NVOsJf7WPLO20mYHTNdQJphPW1J52cOCQA+/g/I4O9nXse6sG8Qer1p3Iw=
